### ISSUE TITLE
Ability to zoom

### ISSUE THREAD

**Issue by bpeterme** [vrlandio/vrland_app#40]
would be cool to have a feature that allows to zoom closer to objects and into details with the mouse wheel, like for example here:
https://sketchfab.com/3d-models/buster-drone-294e79652f494130ad2ab00a13fdbafd
or here:
https://www.khronos.org/gltf/

**Comment by arpu** [comment]
@bpeterme  you can run around with WASD and get closer to the object

**Comment by arpu** [comment]
or can you gibe me a sceenshot what object you like to zoom in ?

**Comment by arpu** [comment]
ahh hey @bpeterme  now i know you :>  
will try to get this working, i am not complete sure how this will work and "feel"  with first person view

**Comment by arpu** [comment]
@bpeterme   online with version v0.1.198 in all Rooms
